name: Pull request
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out reposytory code
        uses: actions/checkout@v2
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "students_tests"
          envkey_DATABASE_URL: "postgresql://postgres:postgres@db:5432/students_tests"
          file_name: .env.test
        - name: Run tests
          run: docker-compose -f docker-compose-tests.yml run node_app-ci-cd npm run test